name: CD

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

jobs:
  build_blastem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v9
        with:
          version: 2.0.9

      - run: make blastem -j4

      - name: ZIP Release
        uses: papeloto/action-zip@v1
        with:
          files: example/blastem_libretro.js example/blastem_libretro.wasm index.html main.js vendors
          dest: blastem_libretro.zip

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: blastem_libretro.zip
          asset_name: blastem_libretro.zip
          asset_content_type: application/zip

  build_lutro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v9
        with:
          version: 2.0.9

      - run: make lutro -j4

      - name: ZIP Release
        uses: papeloto/action-zip@v1
        with:
          files: example/lutro_libretro.js example/lutro_libretro.wasm index.html main.js vendors
          dest: lutro_libretro.zip

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: lutro_libretro.zip
          asset_name: lutro_libretro.zip
          asset_content_type: application/zip

