name: CD

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

jobs:
  build_blastem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "VERSION=$(echo ${{ github.event.release.tag_name }} | cut -c 2-)" >> $GITHUB_ENV
      - run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git checkout tags/2.0.9
        echo "13e29bd55185e3c12802bc090b4507901856b2ba" > ./emscripten-releases-tot.txt
        ./emsdk install tot
        ./emsdk activate tot
      - run: make blastem -j4

      - name: ZIP Release
        uses: papeloto/action-zip@v1
        with:
          files: example/blastem_libretro.js extample/blastem_libretro.wasm
          dest: blastem_libretro.zip

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: blastem_libretro.zip
          asset_name: blastem_libretro.zip
          asset_content_type: application/zip


